# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddAssetAllocationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 400)
        MainWindow.setMinimumSize(QtCore.QSize(300, 400))
        MainWindow.setMaximumSize(QtCore.QSize(300, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AddAsset_Title_3 = QtWidgets.QLabel(self.centralwidget)
        self.AddAsset_Title_3.setGeometry(QtCore.QRect(10, 0, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.AddAsset_Title_3.setFont(font)
        self.AddAsset_Title_3.setObjectName("AddAsset_Title_3")
        self.PushButtons_AddAsset_Frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.PushButtons_AddAsset_Frame_3.setGeometry(QtCore.QRect(50, 340, 201, 51))
        self.PushButtons_AddAsset_Frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PushButtons_AddAsset_Frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PushButtons_AddAsset_Frame_3.setObjectName("PushButtons_AddAsset_Frame_3")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout(self.PushButtons_AddAsset_Frame_3)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.Save_AddAsset_Button_3 = QtWidgets.QPushButton(self.PushButtons_AddAsset_Frame_3)
        self.Save_AddAsset_Button_3.setObjectName("Save_AddAsset_Button_3")
        self.horizontalLayout_43.addWidget(self.Save_AddAsset_Button_3)
        self.Cancel_AddAsset_Button_3 = QtWidgets.QPushButton(self.PushButtons_AddAsset_Frame_3)
        self.Cancel_AddAsset_Button_3.setObjectName("Cancel_AddAsset_Button_3")
        self.horizontalLayout_43.addWidget(self.Cancel_AddAsset_Button_3)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 60, 291, 261))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleOfEmployeeID_AddAsset_3 = QtWidgets.QLabel(self.frame)
        self.TitleOfEmployeeID_AddAsset_3.setObjectName("TitleOfEmployeeID_AddAsset_3")
        self.verticalLayout.addWidget(self.TitleOfEmployeeID_AddAsset_3)
        self.TitleOf_ObjectName_AddAsset_3 = QtWidgets.QLabel(self.frame)
        self.TitleOf_ObjectName_AddAsset_3.setObjectName("TitleOf_ObjectName_AddAsset_3")
        self.verticalLayout.addWidget(self.TitleOf_ObjectName_AddAsset_3)
        self.TitleOfQuantity_AddAsset_3 = QtWidgets.QLabel(self.frame)
        self.TitleOfQuantity_AddAsset_3.setObjectName("TitleOfQuantity_AddAsset_3")
        self.verticalLayout.addWidget(self.TitleOfQuantity_AddAsset_3)
        self.TitleOfAuditorID_AddAsset_3 = QtWidgets.QLabel(self.frame)
        self.TitleOfAuditorID_AddAsset_3.setObjectName("TitleOfAuditorID_AddAsset_3")
        self.verticalLayout.addWidget(self.TitleOfAuditorID_AddAsset_3)
        self.SuggestedReturnDate_Title_AddAsset_3 = QtWidgets.QLabel(self.frame)
        self.SuggestedReturnDate_Title_AddAsset_3.setObjectName("SuggestedReturnDate_Title_AddAsset_3")
        self.verticalLayout.addWidget(self.SuggestedReturnDate_Title_AddAsset_3)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.EmployeeID_input_AddAsset_3 = QtWidgets.QLineEdit(self.frame_2)
        self.EmployeeID_input_AddAsset_3.setObjectName("EmployeeID_input_AddAsset_3")
        self.verticalLayout_2.addWidget(self.EmployeeID_input_AddAsset_3)
        self.ObjectName_Enum = QtWidgets.QComboBox(self.frame_2)
        self.ObjectName_Enum.setObjectName("ObjectName_Enum")
        self.verticalLayout_2.addWidget(self.ObjectName_Enum)
        self.Quantity_input_AddAsset_3 = QtWidgets.QLineEdit(self.frame_2)
        self.Quantity_input_AddAsset_3.setObjectName("Quantity_input_AddAsset_3")
        self.verticalLayout_2.addWidget(self.Quantity_input_AddAsset_3)
        self.AuditorID_Input_AddAssest_3 = QtWidgets.QLineEdit(self.frame_2)
        self.AuditorID_Input_AddAssest_3.setObjectName("AuditorID_Input_AddAssest_3")
        self.verticalLayout_2.addWidget(self.AuditorID_Input_AddAssest_3)
        self.SuggestedReturnDate_Input_AddAsset_3 = QtWidgets.QDateEdit(self.frame_2)
        self.SuggestedReturnDate_Input_AddAsset_3.setObjectName("SuggestedReturnDate_Input_AddAsset_3")
        self.verticalLayout_2.addWidget(self.SuggestedReturnDate_Input_AddAsset_3)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AddAsset_Title_3.setText(_translate("MainWindow", "Asset allocation"))
        self.Save_AddAsset_Button_3.setText(_translate("MainWindow", "Add"))
        self.Cancel_AddAsset_Button_3.setText(_translate("MainWindow", "Cancel"))
        self.TitleOfEmployeeID_AddAsset_3.setText(_translate("MainWindow", "Employee ID:"))
        self.TitleOf_ObjectName_AddAsset_3.setText(_translate("MainWindow", "Object name:"))
        self.TitleOfQuantity_AddAsset_3.setText(_translate("MainWindow", "Quantity:"))
        self.TitleOfAuditorID_AddAsset_3.setText(_translate("MainWindow", "Auditor ID:"))
        self.SuggestedReturnDate_Title_AddAsset_3.setText(_translate("MainWindow", "Suggested return date:"))


class AddAssetAllocationWindow (QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self = self.setupUi(self)

    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
