# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddAssetInventory.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 450)
        MainWindow.setMinimumSize(QtCore.QSize(300, 450))
        MainWindow.setMaximumSize(QtCore.QSize(300, 450))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Add_Assets_Inventory_Title_3 = QtWidgets.QLabel(self.centralwidget)
        self.Add_Assets_Inventory_Title_3.setGeometry(QtCore.QRect(60, 0, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.Add_Assets_Inventory_Title_3.setFont(font)
        self.Add_Assets_Inventory_Title_3.setObjectName("Add_Assets_Inventory_Title_3")
        self.PushButtons_AddAssets_Inventory_Frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.PushButtons_AddAssets_Inventory_Frame_4.setGeometry(QtCore.QRect(50, 380, 191, 43))
        self.PushButtons_AddAssets_Inventory_Frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PushButtons_AddAssets_Inventory_Frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PushButtons_AddAssets_Inventory_Frame_4.setObjectName("PushButtons_AddAssets_Inventory_Frame_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.PushButtons_AddAssets_Inventory_Frame_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Save_AddAssets_Inventory_Button_4 = QtWidgets.QPushButton(self.PushButtons_AddAssets_Inventory_Frame_4)
        self.Save_AddAssets_Inventory_Button_4.setObjectName("Save_AddAssets_Inventory_Button_4")
        self.horizontalLayout_6.addWidget(self.Save_AddAssets_Inventory_Button_4)
        self.Cancel_AddAssets_Inventory_Button_4 = QtWidgets.QPushButton(self.PushButtons_AddAssets_Inventory_Frame_4)
        self.Cancel_AddAssets_Inventory_Button_4.setObjectName("Cancel_AddAssets_Inventory_Button_4")
        self.horizontalLayout_6.addWidget(self.Cancel_AddAssets_Inventory_Button_4)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 59, 268, 311))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TitleOf_ObjectName_AddAsset_4 = QtWidgets.QLabel(self.frame)
        self.TitleOf_ObjectName_AddAsset_4.setObjectName("TitleOf_ObjectName_AddAsset_4")
        self.verticalLayout_2.addWidget(self.TitleOf_ObjectName_AddAsset_4)
        self.TitleOf_SerialNumber_AddAsset_4 = QtWidgets.QLabel(self.frame)
        self.TitleOf_SerialNumber_AddAsset_4.setObjectName("TitleOf_SerialNumber_AddAsset_4")
        self.verticalLayout_2.addWidget(self.TitleOf_SerialNumber_AddAsset_4)
        self.TitleOfQuantity_AddAsset_4 = QtWidgets.QLabel(self.frame)
        self.TitleOfQuantity_AddAsset_4.setObjectName("TitleOfQuantity_AddAsset_4")
        self.verticalLayout_2.addWidget(self.TitleOfQuantity_AddAsset_4)
        self.TitleOf_MoneyValue_AddAsset_4 = QtWidgets.QLabel(self.frame)
        self.TitleOf_MoneyValue_AddAsset_4.setObjectName("TitleOf_MoneyValue_AddAsset_4")
        self.verticalLayout_2.addWidget(self.TitleOf_MoneyValue_AddAsset_4)
        self.TitleOf_Location_AddAsset_5 = QtWidgets.QLabel(self.frame)
        self.TitleOf_Location_AddAsset_5.setObjectName("TitleOf_Location_AddAsset_5")
        self.verticalLayout_2.addWidget(self.TitleOf_Location_AddAsset_5)
        self.TitleOfdescription_AddAsset_4 = QtWidgets.QLabel(self.frame)
        self.TitleOfdescription_AddAsset_4.setObjectName("TitleOfdescription_AddAsset_4")
        self.verticalLayout_2.addWidget(self.TitleOfdescription_AddAsset_4)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ObjectName_input_AddAssets_Inventory_4 = QtWidgets.QLineEdit(self.frame_2)
        self.ObjectName_input_AddAssets_Inventory_4.setObjectName("ObjectName_input_AddAssets_Inventory_4")
        self.verticalLayout.addWidget(self.ObjectName_input_AddAssets_Inventory_4)
        self.SerialNumber_input_AddAssets_Inventory_4 = QtWidgets.QLineEdit(self.frame_2)
        self.SerialNumber_input_AddAssets_Inventory_4.setObjectName("SerialNumber_input_AddAssets_Inventory_4")
        self.verticalLayout.addWidget(self.SerialNumber_input_AddAssets_Inventory_4)
        self.Quantity_input_AddAssets_Inventory_4 = QtWidgets.QLineEdit(self.frame_2)
        self.Quantity_input_AddAssets_Inventory_4.setObjectName("Quantity_input_AddAssets_Inventory_4")
        self.verticalLayout.addWidget(self.Quantity_input_AddAssets_Inventory_4)
        self.MoneyValue_input_AddAssets_Inventory_4 = QtWidgets.QLineEdit(self.frame_2)
        self.MoneyValue_input_AddAssets_Inventory_4.setObjectName("MoneyValue_input_AddAssets_Inventory_4")
        self.verticalLayout.addWidget(self.MoneyValue_input_AddAssets_Inventory_4)
        self.Location_input_AddAssets_Inventory_5 = QtWidgets.QLineEdit(self.frame_2)
        self.Location_input_AddAssets_Inventory_5.setObjectName("Location_input_AddAssets_Inventory_5")
        self.verticalLayout.addWidget(self.Location_input_AddAssets_Inventory_5)
        self.description_Input_AddAssets_Inventory_4 = QtWidgets.QLineEdit(self.frame_2)
        self.description_Input_AddAssets_Inventory_4.setObjectName("description_Input_AddAssets_Inventory_4")
        self.verticalLayout.addWidget(self.description_Input_AddAssets_Inventory_4)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Add_Assets_Inventory_Title_3.setText(_translate("MainWindow", "Add Asset  "))
        self.Save_AddAssets_Inventory_Button_4.setText(_translate("MainWindow", "Add"))
        self.Cancel_AddAssets_Inventory_Button_4.setText(_translate("MainWindow", "Cancel"))
        self.TitleOf_ObjectName_AddAsset_4.setText(_translate("MainWindow", "Object name:"))
        self.TitleOf_SerialNumber_AddAsset_4.setText(_translate("MainWindow", "Serial number:"))
        self.TitleOfQuantity_AddAsset_4.setText(_translate("MainWindow", "Quantity:"))
        self.TitleOf_MoneyValue_AddAsset_4.setText(_translate("MainWindow", "Money value:"))
        self.TitleOf_Location_AddAsset_5.setText(_translate("MainWindow", "Location"))
        self.TitleOfdescription_AddAsset_4.setText(_translate("MainWindow", "description"))


class AddAssetInventory (QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self = self.setupUi(self)

    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
