# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddDepartmentWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 350)
        MainWindow.setMinimumSize(QtCore.QSize(300, 350))
        MainWindow.setMaximumSize(QtCore.QSize(300, 350))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PushButtons_AddPayment_Frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.PushButtons_AddPayment_Frame_3.setGeometry(QtCore.QRect(0, 290, 290, 50))
        self.PushButtons_AddPayment_Frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PushButtons_AddPayment_Frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PushButtons_AddPayment_Frame_3.setObjectName("PushButtons_AddPayment_Frame_3")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.PushButtons_AddPayment_Frame_3)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.Save_AddDepartment_Button_3 = QtWidgets.QPushButton(self.PushButtons_AddPayment_Frame_3)
        self.Save_AddDepartment_Button_3.setObjectName("Save_AddDepartment_Button_3")
        self.horizontalLayout_16.addWidget(self.Save_AddDepartment_Button_3)
        self.Cancel_AddDepartment_Button_3 = QtWidgets.QPushButton(self.PushButtons_AddPayment_Frame_3)
        self.Cancel_AddDepartment_Button_3.setObjectName("Cancel_AddDepartment_Button_3")
        self.horizontalLayout_16.addWidget(self.Cancel_AddDepartment_Button_3)
        self.Add_Department_TitleOf_Table_4 = QtWidgets.QLabel(self.centralwidget)
        self.Add_Department_TitleOf_Table_4.setGeometry(QtCore.QRect(50, 20, 201, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Add_Department_TitleOf_Table_4.sizePolicy().hasHeightForWidth())
        self.Add_Department_TitleOf_Table_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.Add_Department_TitleOf_Table_4.setFont(font)
        self.Add_Department_TitleOf_Table_4.setObjectName("Add_Department_TitleOf_Table_4")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(14, 75, 261, 191))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleOf_DepartmentName_AddDepartment_7 = QtWidgets.QLabel(self.frame)
        self.TitleOf_DepartmentName_AddDepartment_7.setObjectName("TitleOf_DepartmentName_AddDepartment_7")
        self.verticalLayout.addWidget(self.TitleOf_DepartmentName_AddDepartment_7)
        self.TitleOfManagerID_AddDepartment_2 = QtWidgets.QLabel(self.frame)
        self.TitleOfManagerID_AddDepartment_2.setObjectName("TitleOfManagerID_AddDepartment_2")
        self.verticalLayout.addWidget(self.TitleOfManagerID_AddDepartment_2)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Name_input_AddDepartment_7 = QtWidgets.QLineEdit(self.frame_2)
        self.Name_input_AddDepartment_7.setObjectName("Name_input_AddDepartment_7")
        self.verticalLayout_2.addWidget(self.Name_input_AddDepartment_7)
        self.ManagerID_Input_2 = QtWidgets.QLineEdit(self.frame_2)
        self.ManagerID_Input_2.setObjectName("ManagerID_Input_2")
        self.verticalLayout_2.addWidget(self.ManagerID_Input_2)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Save_AddDepartment_Button_3.setText(_translate("MainWindow", "Add"))
        self.Cancel_AddDepartment_Button_3.setText(_translate("MainWindow", "Cancel"))
        self.Add_Department_TitleOf_Table_4.setText(_translate("MainWindow", "Department"))
        self.TitleOf_DepartmentName_AddDepartment_7.setText(_translate("MainWindow", "Name"))
        self.TitleOfManagerID_AddDepartment_2.setText(_translate("MainWindow", "Manager ID"))


class AddDepartmentWindow (QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self = self.setupUi(self)

    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
