# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddLoanWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 450)
        MainWindow.setMinimumSize(QtCore.QSize(300, 450))
        MainWindow.setMaximumSize(QtCore.QSize(300, 450))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AddLoan_Title_4 = QtWidgets.QLabel(self.centralwidget)
        self.AddLoan_Title_4.setGeometry(QtCore.QRect(80, 30, 140, 39))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.AddLoan_Title_4.setFont(font)
        self.AddLoan_Title_4.setObjectName("AddLoan_Title_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(50, 390, 176, 43))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Save_AddLoan_Button_4 = QtWidgets.QPushButton(self.frame)
        self.Save_AddLoan_Button_4.setObjectName("Save_AddLoan_Button_4")
        self.horizontalLayout.addWidget(self.Save_AddLoan_Button_4)
        self.Cancel_AddLoan_Button_4 = QtWidgets.QPushButton(self.frame)
        self.Cancel_AddLoan_Button_4.setObjectName("Cancel_AddLoan_Button_4")
        self.horizontalLayout.addWidget(self.Cancel_AddLoan_Button_4)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 80, 301, 301))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TitleOfEmployeeID_AddLoan_4 = QtWidgets.QLabel(self.frame_2)
        self.TitleOfEmployeeID_AddLoan_4.setObjectName("TitleOfEmployeeID_AddLoan_4")
        self.verticalLayout_2.addWidget(self.TitleOfEmployeeID_AddLoan_4)
        self.TitleOfAmount_AddLoan_4 = QtWidgets.QLabel(self.frame_2)
        self.TitleOfAmount_AddLoan_4.setObjectName("TitleOfAmount_AddLoan_4")
        self.verticalLayout_2.addWidget(self.TitleOfAmount_AddLoan_4)
        self.TypeofDeposit_title_4 = QtWidgets.QLabel(self.frame_2)
        self.TypeofDeposit_title_4.setObjectName("TypeofDeposit_title_4")
        self.verticalLayout_2.addWidget(self.TypeofDeposit_title_4)
        self.TitleOfAuditorID_AddLoan_4 = QtWidgets.QLabel(self.frame_2)
        self.TitleOfAuditorID_AddLoan_4.setObjectName("TitleOfAuditorID_AddLoan_4")
        self.verticalLayout_2.addWidget(self.TitleOfAuditorID_AddLoan_4)
        self.LoanType_title_4 = QtWidgets.QLabel(self.frame_2)
        self.LoanType_title_4.setObjectName("LoanType_title_4")
        self.verticalLayout_2.addWidget(self.LoanType_title_4)
        self.SuggestedReturnDate_Title_AddLoan_4 = QtWidgets.QLabel(self.frame_2)
        self.SuggestedReturnDate_Title_AddLoan_4.setObjectName("SuggestedReturnDate_Title_AddLoan_4")
        self.verticalLayout_2.addWidget(self.SuggestedReturnDate_Title_AddLoan_4)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.EmployeeID_input_AddLoan_4 = QtWidgets.QLineEdit(self.frame_4)
        self.EmployeeID_input_AddLoan_4.setObjectName("EmployeeID_input_AddLoan_4")
        self.verticalLayout.addWidget(self.EmployeeID_input_AddLoan_4)
        self.LoanAmount_Input_4 = QtWidgets.QLineEdit(self.frame_4)
        self.LoanAmount_Input_4.setObjectName("LoanAmount_Input_4")
        self.verticalLayout.addWidget(self.LoanAmount_Input_4)
        self.TypeofDeposit_Enum_4 = QtWidgets.QComboBox(self.frame_4)
        self.TypeofDeposit_Enum_4.setMinimumSize(QtCore.QSize(90, 0))
        self.TypeofDeposit_Enum_4.setMaximumSize(QtCore.QSize(90, 16777215))
        self.TypeofDeposit_Enum_4.setObjectName("TypeofDeposit_Enum_4")
        self.verticalLayout.addWidget(self.TypeofDeposit_Enum_4)
        self.AuditorID_Input_AddLoan_4 = QtWidgets.QLineEdit(self.frame_4)
        self.AuditorID_Input_AddLoan_4.setObjectName("AuditorID_Input_AddLoan_4")
        self.verticalLayout.addWidget(self.AuditorID_Input_AddLoan_4)
        self.LoanType_Enum_4 = QtWidgets.QComboBox(self.frame_4)
        self.LoanType_Enum_4.setMinimumSize(QtCore.QSize(90, 0))
        self.LoanType_Enum_4.setMaximumSize(QtCore.QSize(90, 16777215))
        self.LoanType_Enum_4.setObjectName("LoanType_Enum_4")
        self.verticalLayout.addWidget(self.LoanType_Enum_4)
        self.SuggestedReturnDate_Input_AddLoan_4 = QtWidgets.QDateEdit(self.frame_4)
        self.SuggestedReturnDate_Input_AddLoan_4.setObjectName("SuggestedReturnDate_Input_AddLoan_4")
        self.verticalLayout.addWidget(self.SuggestedReturnDate_Input_AddLoan_4)

        self.horizontalLayout_2.addWidget(self.frame_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AddLoan_Title_4.setText(_translate("MainWindow", "Add loan"))
        self.Save_AddLoan_Button_4.setText(_translate("MainWindow", "Add"))
        self.Cancel_AddLoan_Button_4.setText(_translate("MainWindow", "Cancel"))
        self.TitleOfEmployeeID_AddLoan_4.setText(_translate("MainWindow", "Employee ID:"))
        self.TitleOfAmount_AddLoan_4.setText(_translate("MainWindow", "Amount:"))
        self.TypeofDeposit_title_4.setText(_translate("MainWindow", "Type of deposit:"))
        self.TitleOfAuditorID_AddLoan_4.setText(_translate("MainWindow", "Auditor ID:"))
        self.LoanType_title_4.setText(_translate("MainWindow", "Loan type:"))
        self.SuggestedReturnDate_Title_AddLoan_4.setText(_translate("MainWindow", "Suggested return date:"))


class AddLoanWindow (QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self = self.setupUi(self)

    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
