# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddUserWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 300)
        MainWindow.setMinimumSize(QtCore.QSize(300, 300))
        MainWindow.setMaximumSize(QtCore.QSize(300, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AddAuditor_Title_2 = QtWidgets.QLabel(self.centralwidget)
        self.AddAuditor_Title_2.setGeometry(QtCore.QRect(60, 0, 191, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.AddAuditor_Title_2.setFont(font)
        self.AddAuditor_Title_2.setObjectName("AddAuditor_Title_2")
        self.PushButtons_AddAuditor_Frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.PushButtons_AddAuditor_Frame_3.setGeometry(QtCore.QRect(60, 250, 176, 43))
        self.PushButtons_AddAuditor_Frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PushButtons_AddAuditor_Frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PushButtons_AddAuditor_Frame_3.setObjectName("PushButtons_AddAuditor_Frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.PushButtons_AddAuditor_Frame_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Save_AddAuditor_Button = QtWidgets.QPushButton(self.PushButtons_AddAuditor_Frame_3)
        self.Save_AddAuditor_Button.setObjectName("Save_AddAuditor_Button")
        self.horizontalLayout_5.addWidget(self.Save_AddAuditor_Button)
        self.Cancel_AddAuditor_Button = QtWidgets.QPushButton(self.PushButtons_AddAuditor_Frame_3)
        self.Cancel_AddAuditor_Button.setObjectName("Cancel_AddAuditor_Button")
        self.horizontalLayout_5.addWidget(self.Cancel_AddAuditor_Button)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 57, 263, 181))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TitleOfEmployeeID_AddAuditor_2 = QtWidgets.QLabel(self.frame)
        self.TitleOfEmployeeID_AddAuditor_2.setObjectName("TitleOfEmployeeID_AddAuditor_2")
        self.verticalLayout_2.addWidget(self.TitleOfEmployeeID_AddAuditor_2)
        self.TitleOfUsername_AddAuditor_2 = QtWidgets.QLabel(self.frame)
        self.TitleOfUsername_AddAuditor_2.setObjectName("TitleOfUsername_AddAuditor_2")
        self.verticalLayout_2.addWidget(self.TitleOfUsername_AddAuditor_2)
        self.TitleOfPassword_AddAuditor_2 = QtWidgets.QLabel(self.frame)
        self.TitleOfPassword_AddAuditor_2.setObjectName("TitleOfPassword_AddAuditor_2")
        self.verticalLayout_2.addWidget(self.TitleOfPassword_AddAuditor_2)
        self.TitleOfAdmin_AddAuditor_2 = QtWidgets.QLabel(self.frame)
        self.TitleOfAdmin_AddAuditor_2.setObjectName("TitleOfAdmin_AddAuditor_2")
        self.verticalLayout_2.addWidget(self.TitleOfAdmin_AddAuditor_2)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.EmployeeID_input_AddAudtior_2 = QtWidgets.QLineEdit(self.frame_2)
        self.EmployeeID_input_AddAudtior_2.setObjectName("EmployeeID_input_AddAudtior_2")
        self.verticalLayout.addWidget(self.EmployeeID_input_AddAudtior_2)
        self.Username_input_AddAudtior_2 = QtWidgets.QLineEdit(self.frame_2)
        self.Username_input_AddAudtior_2.setObjectName("Username_input_AddAudtior_2")
        self.verticalLayout.addWidget(self.Username_input_AddAudtior_2)
        self.Password_input_AddAudtior_2 = QtWidgets.QLineEdit(self.frame_2)
        self.Password_input_AddAudtior_2.setObjectName("Password_input_AddAudtior_2")
        self.Password_input_AddAudtior_2.setEchoMode(2)
        self.verticalLayout.addWidget(self.Password_input_AddAudtior_2)
        self.Admin_Enum_AddAudtior_2 = QtWidgets.QComboBox(self.frame_2)
        self.Admin_Enum_AddAudtior_2.setMinimumSize(QtCore.QSize(50, 0))
        self.Admin_Enum_AddAudtior_2.setObjectName("Admin_Enum_AddAudtior_2")
        self.verticalLayout.addWidget(self.Admin_Enum_AddAudtior_2)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AddAuditor_Title_2.setText(_translate("MainWindow", "Add User"))
        self.Save_AddAuditor_Button.setText(_translate("MainWindow", "Add"))
        self.Cancel_AddAuditor_Button.setText(_translate("MainWindow", "Cancel"))
        self.TitleOfEmployeeID_AddAuditor_2.setText(_translate("MainWindow", "Employee ID:"))
        self.TitleOfUsername_AddAuditor_2.setText(_translate("MainWindow", "Username:"))
        self.TitleOfPassword_AddAuditor_2.setText(_translate("MainWindow", "Password:"))
        self.TitleOfAdmin_AddAuditor_2.setText(_translate("MainWindow", "Admin"))


class AddUserWindow (QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self = self.setupUi(self)

    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
