# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditAssetInventory.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 450)
        MainWindow.setMinimumSize(QtCore.QSize(300, 450))
        MainWindow.setMaximumSize(QtCore.QSize(300, 450))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Add_Assets_Inventory_Title_4 = QtWidgets.QLabel(self.centralwidget)
        self.Add_Assets_Inventory_Title_4.setGeometry(QtCore.QRect(60, 10, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.Add_Assets_Inventory_Title_4.setFont(font)
        self.Add_Assets_Inventory_Title_4.setObjectName("Add_Assets_Inventory_Title_4")
        self.PushButtons_UpdateAEmployee_Frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.PushButtons_UpdateAEmployee_Frame_3.setGeometry(QtCore.QRect(70, 390, 176, 43))
        self.PushButtons_UpdateAEmployee_Frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PushButtons_UpdateAEmployee_Frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PushButtons_UpdateAEmployee_Frame_3.setObjectName("PushButtons_UpdateAEmployee_Frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.PushButtons_UpdateAEmployee_Frame_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Save_UpdateAssets_Inventory_Button_3 = QtWidgets.QPushButton(self.PushButtons_UpdateAEmployee_Frame_3)
        self.Save_UpdateAssets_Inventory_Button_3.setObjectName("Save_UpdateAssets_Inventory_Button_3")
        self.horizontalLayout_6.addWidget(self.Save_UpdateAssets_Inventory_Button_3)
        self.Cancel_UpdateAssets_Inventory_Button_3 = QtWidgets.QPushButton(self.PushButtons_UpdateAEmployee_Frame_3)
        self.Cancel_UpdateAssets_Inventory_Button_3.setObjectName("Cancel_UpdateAssets_Inventory_Button_3")
        self.horizontalLayout_6.addWidget(self.Cancel_UpdateAssets_Inventory_Button_3)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 69, 268, 311))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleOf_ObjectName_EditAsset_5 = QtWidgets.QLabel(self.frame_2)
        self.TitleOf_ObjectName_EditAsset_5.setObjectName("TitleOf_ObjectName_EditAsset_5")
        self.verticalLayout.addWidget(self.TitleOf_ObjectName_EditAsset_5)
        self.TitleOf_SerialNumber_EditAsset_5 = QtWidgets.QLabel(self.frame_2)
        self.TitleOf_SerialNumber_EditAsset_5.setObjectName("TitleOf_SerialNumber_EditAsset_5")
        self.verticalLayout.addWidget(self.TitleOf_SerialNumber_EditAsset_5)
        self.TitleOfQuantity_EditAsset_5 = QtWidgets.QLabel(self.frame_2)
        self.TitleOfQuantity_EditAsset_5.setObjectName("TitleOfQuantity_EditAsset_5")
        self.verticalLayout.addWidget(self.TitleOfQuantity_EditAsset_5)
        self.TitleOf_MoneyValue_EditAsset_5 = QtWidgets.QLabel(self.frame_2)
        self.TitleOf_MoneyValue_EditAsset_5.setObjectName("TitleOf_MoneyValue_EditAsset_5")
        self.verticalLayout.addWidget(self.TitleOf_MoneyValue_EditAsset_5)
        self.TitleOf_Location_EditAsset_6 = QtWidgets.QLabel(self.frame_2)
        self.TitleOf_Location_EditAsset_6.setObjectName("TitleOf_Location_EditAsset_6")
        self.verticalLayout.addWidget(self.TitleOf_Location_EditAsset_6)
        self.TitleOfdescription_EditAsset_5 = QtWidgets.QLabel(self.frame_2)
        self.TitleOfdescription_EditAsset_5.setObjectName("TitleOfdescription_EditAsset_5")
        self.verticalLayout.addWidget(self.TitleOfdescription_EditAsset_5)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ObjectName_input_EditAssets_Inventory_5 = QtWidgets.QLineEdit(self.frame_3)
        self.ObjectName_input_EditAssets_Inventory_5.setObjectName("ObjectName_input_EditAssets_Inventory_5")
        self.verticalLayout_2.addWidget(self.ObjectName_input_EditAssets_Inventory_5)
        self.SerialNumber_input_EditAssets_Inventory_5 = QtWidgets.QLineEdit(self.frame_3)
        self.SerialNumber_input_EditAssets_Inventory_5.setObjectName("SerialNumber_input_EditAssets_Inventory_5")
        self.verticalLayout_2.addWidget(self.SerialNumber_input_EditAssets_Inventory_5)
        self.Quantity_input_EditAssets_Inventory_5 = QtWidgets.QLineEdit(self.frame_3)
        self.Quantity_input_EditAssets_Inventory_5.setObjectName("Quantity_input_EditAssets_Inventory_5")
        self.verticalLayout_2.addWidget(self.Quantity_input_EditAssets_Inventory_5)
        self.MoneyValue_input_EditAssets_Inventory_5 = QtWidgets.QLineEdit(self.frame_3)
        self.MoneyValue_input_EditAssets_Inventory_5.setObjectName("MoneyValue_input_EditAssets_Inventory_5")
        self.verticalLayout_2.addWidget(self.MoneyValue_input_EditAssets_Inventory_5)
        self.Location_input_EditAssets_Inventory_6 = QtWidgets.QLineEdit(self.frame_3)
        self.Location_input_EditAssets_Inventory_6.setObjectName("Location_input_EditAssets_Inventory_6")
        self.verticalLayout_2.addWidget(self.Location_input_EditAssets_Inventory_6)
        self.description_Input_EditAssets_Inventory_5 = QtWidgets.QLineEdit(self.frame_3)
        self.description_Input_EditAssets_Inventory_5.setObjectName("description_Input_EditAssets_Inventory_5")
        self.verticalLayout_2.addWidget(self.description_Input_EditAssets_Inventory_5)
        self.horizontalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Add_Assets_Inventory_Title_4.setText(_translate("MainWindow", "Edit Asset"))
        self.Save_UpdateAssets_Inventory_Button_3.setText(_translate("MainWindow", "Update"))
        self.Cancel_UpdateAssets_Inventory_Button_3.setText(_translate("MainWindow", "Cancel"))
        self.TitleOf_ObjectName_EditAsset_5.setText(_translate("MainWindow", "Object name:"))
        self.TitleOf_SerialNumber_EditAsset_5.setText(_translate("MainWindow", "Serial number:"))
        self.TitleOfQuantity_EditAsset_5.setText(_translate("MainWindow", "Quantity:"))
        self.TitleOf_MoneyValue_EditAsset_5.setText(_translate("MainWindow", "Money value:"))
        self.TitleOf_Location_EditAsset_6.setText(_translate("MainWindow", "Location"))
        self.TitleOfdescription_EditAsset_5.setText(_translate("MainWindow", "Description"))


class EditAssetInventory (QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self = self.setupUi(self)

    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
