# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditLoanWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 450)
        MainWindow.setMinimumSize(QtCore.QSize(300, 450))
        MainWindow.setMaximumSize(QtCore.QSize(300, 450))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.EditLoan_Title_4 = QtWidgets.QLabel(self.centralwidget)
        self.EditLoan_Title_4.setGeometry(QtCore.QRect(80, 30, 141, 39))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.EditLoan_Title_4.setFont(font)
        self.EditLoan_Title_4.setObjectName("EditLoan_Title_4")
        self.Input_EditLoan_Frame1_4 = QtWidgets.QFrame(self.centralwidget)
        self.Input_EditLoan_Frame1_4.setGeometry(QtCore.QRect(9, 95, 281, 339))
        self.Input_EditLoan_Frame1_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Input_EditLoan_Frame1_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Input_EditLoan_Frame1_4.setObjectName("Input_EditLoan_Frame1_4")
        self.gridLayout = QtWidgets.QGridLayout(self.Input_EditLoan_Frame1_4)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_6 = QtWidgets.QFrame(self.Input_EditLoan_Frame1_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.LoanType_title_4 = QtWidgets.QLabel(self.frame_6)
        self.LoanType_title_4.setObjectName("LoanType_title_4")
        self.horizontalLayout_6.addWidget(self.LoanType_title_4)
        self.LoanType_Enum_5 = QtWidgets.QComboBox(self.frame_6)
        self.LoanType_Enum_5.setMinimumSize(QtCore.QSize(90, 0))
        self.LoanType_Enum_5.setMaximumSize(QtCore.QSize(90, 16777215))
        self.LoanType_Enum_5.setObjectName("LoanType_Enum_5")
        self.horizontalLayout_6.addWidget(self.LoanType_Enum_5)
        self.gridLayout.addWidget(self.frame_6, 2, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.Input_EditLoan_Frame1_4)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.TitleOfAmount_EditLoan_4 = QtWidgets.QLabel(self.frame_3)
        self.TitleOfAmount_EditLoan_4.setObjectName("TitleOfAmount_EditLoan_4")
        self.horizontalLayout_3.addWidget(self.TitleOfAmount_EditLoan_4)
        spacerItem = QtWidgets.QSpacerItem(62, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.LoanAmount_Input_5 = QtWidgets.QLineEdit(self.frame_3)
        self.LoanAmount_Input_5.setObjectName("LoanAmount_Input_5")
        self.horizontalLayout_3.addWidget(self.LoanAmount_Input_5)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.Input_EditLoan_Frame1_4)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.TypeofDeposit_title_4 = QtWidgets.QLabel(self.frame_2)
        self.TypeofDeposit_title_4.setObjectName("TypeofDeposit_title_4")
        self.horizontalLayout_2.addWidget(self.TypeofDeposit_title_4)
        self.TypeofDeposit_Enum_5 = QtWidgets.QComboBox(self.frame_2)
        self.TypeofDeposit_Enum_5.setMinimumSize(QtCore.QSize(90, 0))
        self.TypeofDeposit_Enum_5.setMaximumSize(QtCore.QSize(90, 16777215))
        self.TypeofDeposit_Enum_5.setObjectName("TypeofDeposit_Enum_5")
        self.horizontalLayout_2.addWidget(self.TypeofDeposit_Enum_5)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.PushButtons_EditPayment_Frame_5 = QtWidgets.QFrame(self.Input_EditLoan_Frame1_4)
        self.PushButtons_EditPayment_Frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PushButtons_EditPayment_Frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PushButtons_EditPayment_Frame_5.setObjectName("PushButtons_EditPayment_Frame_5")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.PushButtons_EditPayment_Frame_5)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.Save_EditLoan_Button_4 = QtWidgets.QPushButton(self.PushButtons_EditPayment_Frame_5)
        self.Save_EditLoan_Button_4.setObjectName("Save_EditLoan_Button_4")
        self.horizontalLayout_30.addWidget(self.Save_EditLoan_Button_4)
        self.Cancel_EditLoan_Button_4 = QtWidgets.QPushButton(self.PushButtons_EditPayment_Frame_5)
        self.Cancel_EditLoan_Button_4.setObjectName("Cancel_EditLoan_Button_4")
        self.horizontalLayout_30.addWidget(self.Cancel_EditLoan_Button_4)
        self.gridLayout.addWidget(self.PushButtons_EditPayment_Frame_5, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.LoanAmount_Input_5, self.TypeofDeposit_Enum_5)
        MainWindow.setTabOrder(self.TypeofDeposit_Enum_5, self.LoanType_Enum_5)
        MainWindow.setTabOrder(self.LoanType_Enum_5, self.Save_EditLoan_Button_4)
        MainWindow.setTabOrder(self.Save_EditLoan_Button_4, self.Cancel_EditLoan_Button_4)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.EditLoan_Title_4.setText(_translate("MainWindow", "Edit loan"))
        self.LoanType_title_4.setText(_translate("MainWindow", "Loan type:"))
        self.TitleOfAmount_EditLoan_4.setText(_translate("MainWindow", "Amount:"))
        self.TypeofDeposit_title_4.setText(_translate("MainWindow", "Type of deposit:"))
        self.Save_EditLoan_Button_4.setText(_translate("MainWindow", "Add"))
        self.Cancel_EditLoan_Button_4.setText(_translate("MainWindow", "Cancel"))


class EditLoanWindow (QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self = self.setupUi(self)

    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
