# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditPaymentWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 350)
        MainWindow.setMinimumSize(QtCore.QSize(300, 350))
        MainWindow.setMaximumSize(QtCore.QSize(300, 350))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 60, 261, 198))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.TitleOfAmount_EditPayment_2 = QtWidgets.QLabel(self.frame_3)
        self.TitleOfAmount_EditPayment_2.setObjectName("TitleOfAmount_EditPayment_2")
        self.horizontalLayout_2.addWidget(self.TitleOfAmount_EditPayment_2)
        spacerItem = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.PaymentAmount_Input_3 = QtWidgets.QLineEdit(self.frame_3)
        self.PaymentAmount_Input_3.setObjectName("PaymentAmount_Input_3")
        self.horizontalLayout_2.addWidget(self.PaymentAmount_Input_3)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.PaymentMethod_title_2 = QtWidgets.QLabel(self.frame_5)
        self.PaymentMethod_title_2.setObjectName("PaymentMethod_title_2")
        self.horizontalLayout_4.addWidget(self.PaymentMethod_title_2)
        self.PaymentMethod_Enum_3 = QtWidgets.QComboBox(self.frame_5)
        self.PaymentMethod_Enum_3.setMinimumSize(QtCore.QSize(70, 0))
        self.PaymentMethod_Enum_3.setObjectName("PaymentMethod_Enum_3")
        self.horizontalLayout_4.addWidget(self.PaymentMethod_Enum_3)
        self.gridLayout.addWidget(self.frame_5, 1, 0, 1, 1)
        self.PushButtons_AddPayment_Frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.PushButtons_AddPayment_Frame_3.setGeometry(QtCore.QRect(0, 290, 290, 50))
        self.PushButtons_AddPayment_Frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PushButtons_AddPayment_Frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PushButtons_AddPayment_Frame_3.setObjectName("PushButtons_AddPayment_Frame_3")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.PushButtons_AddPayment_Frame_3)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.Save_EditPayment_Button_3 = QtWidgets.QPushButton(self.PushButtons_AddPayment_Frame_3)
        self.Save_EditPayment_Button_3.setObjectName("Save_EditPayment_Button_3")
        self.horizontalLayout_16.addWidget(self.Save_EditPayment_Button_3)
        self.Cancel_EditPayment_Button_3 = QtWidgets.QPushButton(self.PushButtons_AddPayment_Frame_3)
        self.Cancel_EditPayment_Button_3.setObjectName("Cancel_EditPayment_Button_3")
        self.horizontalLayout_16.addWidget(self.Cancel_EditPayment_Button_3)
        self.EditPayment_Title_2 = QtWidgets.QLabel(self.centralwidget)
        self.EditPayment_Title_2.setGeometry(QtCore.QRect(30, 0, 231, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.EditPayment_Title_2.setFont(font)
        self.EditPayment_Title_2.setObjectName("EditPayment_Title_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TitleOfAmount_EditPayment_2.setText(_translate("MainWindow", "Amount:"))
        self.PaymentMethod_title_2.setText(_translate("MainWindow", "Payment method:"))
        self.Save_EditPayment_Button_3.setText(_translate("MainWindow", "Add"))
        self.Cancel_EditPayment_Button_3.setText(_translate("MainWindow", "Cancel"))
        self.EditPayment_Title_2.setText(_translate("MainWindow", "Edit payment"))


class EditPaymentWindow (QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self = self.setupUi(self)

    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
