# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 450)
        MainWindow.setMinimumSize(QtCore.QSize(400, 450))
        MainWindow.setMaximumSize(QtCore.QSize(400, 450))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 401, 451))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.LoginWidget_2 = QtWidgets.QWidget(self.frame)
        self.LoginWidget_2.setGeometry(QtCore.QRect(0, -20, 400, 500))
        self.LoginWidget_2.setMinimumSize(QtCore.QSize(400, 500))
        self.LoginWidget_2.setMaximumSize(QtCore.QSize(400, 500))
        self.LoginWidget_2.setObjectName("LoginWidget_2")
        self.LoginBackground_5 = QtWidgets.QLabel(self.LoginWidget_2)
        self.LoginBackground_5.setGeometry(QtCore.QRect(0, 0, 400, 500))
        self.LoginBackground_5.setMinimumSize(QtCore.QSize(400, 500))
        self.LoginBackground_5.setMaximumSize(QtCore.QSize(400, 500))
        self.LoginBackground_5.setStyleSheet("border-image: url(:/LoginPic/LoginPic.jpg);\n"
"border-radius : 20px;\n"
"\n"
"")
        self.LoginBackground_5.setText("")
        self.LoginBackground_5.setObjectName("LoginBackground_5")
        self.LoginBackground_ForShape = QtWidgets.QLabel(self.LoginWidget_2)
        self.LoginBackground_ForShape.setGeometry(QtCore.QRect(0, 0, 400, 500))
        self.LoginBackground_ForShape.setMinimumSize(QtCore.QSize(400, 500))
        self.LoginBackground_ForShape.setMaximumSize(QtCore.QSize(400, 500))
        self.LoginBackground_ForShape.setStyleSheet("background-color : rgba(0,0,0,100);\n"
"border-radius : 15px;")
        self.LoginBackground_ForShape.setText("")
        self.LoginBackground_ForShape.setObjectName("LoginBackground_ForShape")
        self.Program_Title = QtWidgets.QLabel(self.LoginWidget_2)
        self.Program_Title.setGeometry(QtCore.QRect(70, 60, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Program_Title.setFont(font)
        self.Program_Title.setStyleSheet("color: rgba(255, 255, 255,210);")
        self.Program_Title.setObjectName("Program_Title")
        self.Username_Input = QtWidgets.QLineEdit(self.LoginWidget_2)
        self.Username_Input.setGeometry(QtCore.QRect(80, 165, 231, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Username_Input.setFont(font)
        self.Username_Input.setStyleSheet("background-color : rgba(0,0,0,0);\n"
"border : none;\n"
"border-bottom : 2px solid rgba(105,118,132,255);\n"
"color : rgba(255,255,255,230);\n"
"padding-bottom : 7px;\n"
"")
        self.Username_Input.setText("")
        self.Username_Input.setObjectName("Username_Input")
        self.Password_Input = QtWidgets.QLineEdit(self.LoginWidget_2)
        self.Password_Input.setGeometry(QtCore.QRect(80, 240, 231, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Password_Input.setFont(font)
        self.Password_Input.setStyleSheet("background-color : rgba(0,0,0,0);\n"
"border : none;\n"
"border-bottom : 2px solid rgba(105,118,132,255);\n"
"color : rgba(255,255,255,230);\n"
"padding-bottom : 7px;\n"
"")
        self.Password_Input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password_Input.setObjectName("Password_Input")
        self.Login_Pushbutton = QtWidgets.QPushButton(self.LoginWidget_2)
        self.Login_Pushbutton.setGeometry(QtCore.QRect(115, 330, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Login_Pushbutton.setFont(font)
        self.Login_Pushbutton.setStyleSheet("background-color: rgb(149, 149, 149);\n"
"border-color: rgb(255, 255, 255);")
        self.Login_Pushbutton.setObjectName("Login_Pushbutton")
        self.Languages_Buttons = QtWidgets.QFrame(self.LoginWidget_2)
        self.Languages_Buttons.setGeometry(QtCore.QRect(10, 370, 71, 81))
        self.Languages_Buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Languages_Buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Languages_Buttons.setObjectName("Languages_Buttons")
        self.English_Button = QtWidgets.QRadioButton(self.Languages_Buttons)
        self.English_Button.setGeometry(QtCore.QRect(20, 10, 62, 21))
        self.English_Button.setStyleSheet("color: rgb(255, 255, 255);")
        self.English_Button.setObjectName("English_Button")
        self.Arabic_Button = QtWidgets.QRadioButton(self.Languages_Buttons)
        self.Arabic_Button.setGeometry(QtCore.QRect(20, 50, 62, 21))
        self.Arabic_Button.setStyleSheet("color: rgb(255, 255, 255);")
        self.Arabic_Button.setObjectName("Arabic_Button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Program_Title.setText(_translate("MainWindow", "Asset Management"))
        self.Username_Input.setPlaceholderText(_translate("MainWindow", "Username"))
        self.Password_Input.setPlaceholderText(_translate("MainWindow", "Password"))
        self.Login_Pushbutton.setText(_translate("MainWindow", "L o g i n"))
        self.English_Button.setText(_translate("MainWindow", "Engilsh"))
        self.Arabic_Button.setText(_translate("MainWindow", "العربية"))



class MainWindow (QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self = self.setupUi(self)

    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
