# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UpdateUserWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 300)
        MainWindow.setMinimumSize(QtCore.QSize(300, 300))
        MainWindow.setMaximumSize(QtCore.QSize(300, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PushButtons_UpdateAuditor_Frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.PushButtons_UpdateAuditor_Frame_3.setGeometry(QtCore.QRect(60, 260, 176, 43))
        self.PushButtons_UpdateAuditor_Frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PushButtons_UpdateAuditor_Frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PushButtons_UpdateAuditor_Frame_3.setObjectName("PushButtons_UpdateAuditor_Frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.PushButtons_UpdateAuditor_Frame_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.UpdateAuditor_Button = QtWidgets.QPushButton(self.PushButtons_UpdateAuditor_Frame_3)
        self.UpdateAuditor_Button.setObjectName("UpdateAuditor_Button")
        self.horizontalLayout_5.addWidget(self.UpdateAuditor_Button)
        self.Cancel_UpdateAuditor_Button = QtWidgets.QPushButton(self.PushButtons_UpdateAuditor_Frame_3)
        self.Cancel_UpdateAuditor_Button.setObjectName("Cancel_UpdateAuditor_Button")
        self.horizontalLayout_5.addWidget(self.Cancel_UpdateAuditor_Button)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 50, 259, 201))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleOfEmployeeID_UpdateAuditor_2 = QtWidgets.QLabel(self.frame_2)
        self.TitleOfEmployeeID_UpdateAuditor_2.setObjectName("TitleOfEmployeeID_UpdateAuditor_2")
        self.verticalLayout.addWidget(self.TitleOfEmployeeID_UpdateAuditor_2)
        self.TitleOfUsername_UpdateAuditor_2 = QtWidgets.QLabel(self.frame_2)
        self.TitleOfUsername_UpdateAuditor_2.setObjectName("TitleOfUsername_UpdateAuditor_2")
        self.verticalLayout.addWidget(self.TitleOfUsername_UpdateAuditor_2)
        self.TitleOfPassword_UpdateAuditor_2 = QtWidgets.QLabel(self.frame_2)
        self.TitleOfPassword_UpdateAuditor_2.setObjectName("TitleOfPassword_UpdateAuditor_2")
        self.verticalLayout.addWidget(self.TitleOfPassword_UpdateAuditor_2)
        self.TitleOfAdmin_UpdateAuditor_2 = QtWidgets.QLabel(self.frame_2)
        self.TitleOfAdmin_UpdateAuditor_2.setObjectName("TitleOfAdmin_UpdateAuditor_2")
        self.verticalLayout.addWidget(self.TitleOfAdmin_UpdateAuditor_2)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.EmployeeID_input_UpdateAudtior_2 = QtWidgets.QLineEdit(self.frame_5)
        self.EmployeeID_input_UpdateAudtior_2.setObjectName("EmployeeID_input_UpdateAudtior_2")
        self.verticalLayout_2.addWidget(self.EmployeeID_input_UpdateAudtior_2)
        self.Username_input_UpdateAudtior_2 = QtWidgets.QLineEdit(self.frame_5)
        self.Username_input_UpdateAudtior_2.setObjectName("Username_input_UpdateAudtior_2")
        self.verticalLayout_2.addWidget(self.Username_input_UpdateAudtior_2)
        self.Password_input_UpdateAudtior_2 = QtWidgets.QLineEdit(self.frame_5)
        self.Password_input_UpdateAudtior_2.setObjectName("Password_input_UpdateAudtior_2")
        self.Password_input_UpdateAudtior_2.setEchoMode(2)
        self.verticalLayout_2.addWidget(self.Password_input_UpdateAudtior_2)
        self.Admin_Enum_UpdateAudtior_2 = QtWidgets.QComboBox(self.frame_5)
        self.Admin_Enum_UpdateAudtior_2.setObjectName("Admin_Enum_UpdateAudtior_2")
        self.verticalLayout_2.addWidget(self.Admin_Enum_UpdateAudtior_2)
        self.horizontalLayout.addWidget(self.frame_5)
        self.UpdateAuditor_Title_2 = QtWidgets.QLabel(self.centralwidget)
        self.UpdateAuditor_Title_2.setGeometry(QtCore.QRect(10, 10, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.UpdateAuditor_Title_2.setFont(font)
        self.UpdateAuditor_Title_2.setObjectName("UpdateAuditor_Title_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.UpdateAuditor_Button.setText(_translate("MainWindow", "Update"))
        self.Cancel_UpdateAuditor_Button.setText(_translate("MainWindow", "Cancel"))
        self.TitleOfEmployeeID_UpdateAuditor_2.setText(_translate("MainWindow", "Employee ID"))
        self.TitleOfUsername_UpdateAuditor_2.setText(_translate("MainWindow", "Username"))
        self.TitleOfPassword_UpdateAuditor_2.setText(_translate("MainWindow", "Password"))
        self.TitleOfAdmin_UpdateAuditor_2.setText(_translate("MainWindow", "Admin"))
        self.UpdateAuditor_Title_2.setText(_translate("MainWindow", "Update User"))


class UpdateUserWindow (QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self = self.setupUi(self)

    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
